### ISSUE TITLE
After upgrade to Hrun header2 and header3 don't work

### ISSUE THREAD

**Issue by nathfy** [mwesten/dokuwiki-plugin-header3#2] opened 2014-10-09 11:33 UTC
Get the following in the error log:

using header3 as xhtml renderer 
PHP Fatal error:  Cannot access protected property renderer_plugin_header3::$node in /var/www/html/docuwiki/lib/plugins/header3/syntax.php on line 128, referer:

using header2 as xhtml renderer 
 PHP Fatal error:  Cannot access protected property renderer_plugin_header2::$node in /var/www/html/docuwiki/lib/plugins/header3/syntax.php on line 128

assume base class has changed, will post more if I find it...

**Comment by amazingBytes** [comment] 2014-10-10 13:18
Yes, I can confirm this issue.
Do you have any further findings, yet?

**Comment by nathfy** [comment] 2014-10-10 14:10
No time to look into it further, we've gone back to ponder stibbons for now.

**Comment by amazingBytes** [comment] 2014-10-10 20:44
I've found one provisional solution that worked for me!

Change in DokuWiki's (2014-09-29a "Hrun") XHTML-Renderer /inc/parser/xhtml.php some methods from 'protected' to 'public':

Line 30: protected $sectionedits = array();
change to: public $sectionedits = array();

Line 43: protected $lastlevel = 0;
change to: public $lastlevel = 0;

Line 45: protected $node = array(0, 0, 0, 0, 0);
change to: public $node = array(0, 0, 0, 0, 0);

**Comment by amazingBytes** [comment] 2016-02-03 09:40
Note: Please note my provisional solution ist still working for all newer Versions of DokuWiki

**Comment by Garretby** [comment] 2016-05-02 11:22
Great solution, still work for me and latest version of wiki.

**Comment by amazingBytes** [comment] 2016-06-29 14:25
My solution above is still working with DokuWiki release 2016-06-26 "Elenor of Tsort"

**Comment by amazingBytes** [comment] 2017-05-02 08:07
... and with Release 2017-02-19b "Frusterick Manners", too!

**Comment by mwesten** [comment] 2024-04-25 09:17
Closing this (unresolved) issue.
Dokuwiki Plugin Header:3 became unusable a long time ago, due to changes in Dokuwiki and in PHP.
I'm archiving this repo.

**Closed as not planned by mwesten** 2024-04-25 09:17 UTC
